import express from 'express';
import dotenv from 'dotenv';
dotenv.config();
import * as userController from '../controllers/userController.js';
import { authenticateToken } from '../middleware/auth.js';
const router = express.Router();
router.get('/', userController.getAllUsers);
router.get('/:id',authenticateToken, userController.getUserById);
router.post('/', userController.createUser);
router.post('/login', userController.loginUser);
export default router;